CREATE TABLE IF NOT EXISTS t_charge (
	id INT(11) NOT NULL AUTO_INCREMENT,
	type VARCHAR(100) DEFAULT NULL,
	dateOperation DATE DEFAULT NULL,
	montant DECIMAL(12,2) DEFAULT NULL,
	societe VARCHAR(50) DEFAULT NULL,
	designation VARCHAR(255) DEFAULT NULL,
	idProjet INT(12) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;