CREATE TABLE IF NOT EXISTS t_contratcaslibre (
	id INT(11) NOT NULL AUTO_INCREMENT,
	date DATE DEFAULT NULL,
	montant DECIMAL(12,2) DEFAULT NULL,
	observation TEXT DEFAULT NULL,
	codeContrat VARCHAR(255) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;