CREATE TABLE IF NOT EXISTS t_commandedetail (
	id INT(11) NOT NULL AUTO_INCREMENT,
	reference VARCHAR(100) DEFAULT NULL,
	libelle VARCHAR(50) DEFAULT NULL,
	quantite DECIMAL(12,2) DEFAULT NULL,
	idCommande INT(12) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;