CREATE TABLE IF NOT EXISTS t_employe (
	id INT(11) NOT NULL AUTO_INCREMENT,
	nom VARCHAR(50) DEFAULT NULL,
	adresse VARCHAR(255) DEFAULT NULL,
	nomArabe VARCHAR(50) DEFAULT NULL,
	adresseArabe VARCHAR(255) DEFAULT NULL,
	cin VARCHAR(50) DEFAULT NULL,
	telephone VARCHAR(50) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;