CREATE TABLE IF NOT EXISTS t_relevebancaire (
	id INT(11) NOT NULL AUTO_INCREMENT,
	dateOpe DATE DEFAULT NULL,
	dateVal DATE DEFAULT NULL,
	libelle VARCHAR(255) DEFAULT NULL,
	reference VARCHAR(50) DEFAULT NULL,
	debit DECIMAL(12,2) DEFAULT NULL,
	credit DECIMAL(12,2) DEFAULT NULL,
	projet VARCHAR(50) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;